### ISSUE TITLE
Migrate to latest properties panel version + plugin helpers

### ISSUE THREAD

**Issue by pinussilvestrus** [camunda/camunda-modeler-process-io-specification-plugin#17]
__What should we do?__

* Update to use components over elements (cf. https://github.com/bpmn-io/bpmn-js-examples/issues/160)
* Update to mark plugin as Camunda Platform / C7 only

__Why should we do it?__

The plugin should work smoothly alongside our newest changes.

**Comment by pinussilvestrus** [comment]
Closed via https://github.com/camunda/camunda-modeler-process-io-specification-plugin/pull/18

**Comment by Skaiir** [comment]
My bad, my ticket only covers the second part of this issue. Hence re-opening.

**Comment by pinussilvestrus** [comment]
Good catch 🙂

**Comment by Skaiir** [comment]
Closed via #23
