### ISSUE TITLE
Plugin is not compatible with 5.0.0

### ISSUE THREAD

**Issue by MaxTru** [camunda/camunda-modeler-process-io-specification-plugin#21]
**Issue**

Plugin is not compatabile with 5.0.0

**How to reproduce**

Clone this repo, move into `plugins` of `camunda-modeler` and start camunda modeler.

Now this happens:

![Screenshot_20220317_094255](https://user-images.githubusercontent.com/42800119/158770962-a48ab82a-f8c1-4167-bb90-85b8eb87f913.png)

**Comment by pinussilvestrus** [comment]
I think there needs some updates to be made regarding some breaking properties panel changes: https://github.com/camunda/camunda-modeler-process-io-specification-plugin/issues/17

> Update to use components over elements (cf. https://github.com/bpmn-io/bpmn-js-examples/issues/160)

**Comment by MaxTru** [comment]
@Skaiir please talk to @barmac who already offered his help and follow-up. Thanks

**Comment by barmac** [comment]
For the process io specification plugin, it's mainly migrated to the properties panel alpha.5 via [this branch](https://github.com/camunda/camunda-modeler-process-io-specification-plugin/tree/migrate-to-latest-properties-panel). To make it complete, we need to release and integrate https://github.com/camunda/camunda-bpmn-js

**Comment by MaxTru** [comment]
It doesn't break anymore with https://github.com/camunda/camunda-modeler/pull/2817, but still does not work: one can not add IO specification items

**Comment by Skaiir** [comment]
Closed via #23
